// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMode():Promise<string>;

export function GetSteamAvatar(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenSelf(arg1:string):Promise<void>;
