// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMode() {
  return window['go']['main']['App']['GetMode']();
}

export function GetSteamAvatar(arg1) {
  return window['go']['main']['App']['GetSteamAvatar'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenSelf(arg1) {
  return window['go']['main']['App']['OpenSelf'](arg1);
}
